### ISSUE TITLE
An exception with some types of youtube urls

### ISSUE THREAD

**Issue by alexis** [thibaudgg/video_info#100]
The following code:

    VideoInfo.new('http://www.youtube.com/v/mZqGqE0D0n4').title

Raises an error for me:

```
ArgumentError: string contains null byte
        from /home/vagrant/.rvm/gems/ruby-2.0.0-p451@cmf/gems/oga-1.2.2/lib/oga/xml/lexer.rb:204:in `advance_native'
        from /home/vagrant/.rvm/gems/ruby-2.0.0-p451@cmf/gems/oga-1.2.2/lib/oga/xml/lexer.rb:204:in `block in advance'
        from /home/vagrant/.rvm/gems/ruby-2.0.0-p451@cmf/gems/oga-1.2.2/lib/oga/xml/lexer.rb:147:in `read_data'
        from /home/vagrant/.rvm/gems/ruby-2.0.0-p451@cmf/gems/oga-1.2.2/lib/oga/xml/lexer.rb:203:in `advance'
        from /home/vagrant/.rvm/gems/ruby-2.0.0-p451@cmf/gems/oga-1.2.2/lib/oga/xml/parser.rb:245:in `each_token'
        from /home/vagrant/.rvm/gems/ruby-2.0.0-p451@cmf/gems/oga-1.2.2/lib/oga/xml/parser.rb:282:in `parse'
        from /home/vagrant/.rvm/gems/ruby-2.0.0-p451@cmf/gems/oga-1.2.2/lib/oga/xml/parser.rb:282:in `parse'
        from /home/vagrant/.rvm/gems/ruby-2.0.0-p451@cmf/gems/oga-1.2.2/lib/oga/oga.rb:27:in `parse_html'
        from /home/vagrant/.rvm/gems/ruby-2.0.0-p451@cmf/gems/video_info-2.5.0/lib/video_info/providers/youtube_scraper.rb:91:in `_set_data_from_api'
        from /home/vagrant/.rvm/gems/ruby-2.0.0-p451@cmf/gems/video_info-2.5.0/lib/video_info/provider.rb:32:in `data'
        from /home/vagrant/.rvm/gems/ruby-2.0.0-p451@cmf/gems/video_info-2.5.0/lib/video_info/providers/youtube_scraper.rb:80:in `available?'
        from /home/vagrant/.rvm/gems/ruby-2.0.0-p451@cmf/gems/video_info-2.5.0/lib/video_info/providers/youtube_scraper.rb:60:in `meta_node_value'
        from /home/vagrant/.rvm/gems/ruby-2.0.0-p451@cmf/gems/video_info-2.5.0/lib/video_info/providers/youtube_scraper.rb:34:in `title'
        from (irb):24
```

At the same time, `VideoInfo.new("http://www.youtube.com/watch?v=mZqGqE0D0n4")` works fine. Is it a bug?

**Comment by vheuken** [comment]
The reason you're getting that error with the first type of URL and not the second type is because you're using the parser, and that URL doesn't have anything to parse. Have you tried using the API? See [here](https://github.com/thibaudgg/video_info#usage) for info on how to use it. That being said, I've never tried these types of videos so I'm not sure if it'd work.

Regardless, we should probably handle these types of URLs. Maybe we can grab the ID and generate the second type of URL. I'll have a look this weekend.

**Comment by vheuken** [comment]
I just checked, and that URL appears to work fine with the API, so I'll work on making it work with the scraper.

**Comment by vheuken** [comment]
@alexis I just pushed the fixes to master. Those types of URLs should work with both the scraper and API.

If you'd like to try it without waiting for the next release, you can add this to your Gemfile:

`gem 'video_info', github: 'thibaudgg/video_info'`

**Comment by alexis** [comment]
Thanks, @vheuken
