### ISSUE TITLE
Kernel.open(url) method returns unparseable content for some Youtube links

### ISSUE THREAD

**Issue by 0mega** [thibaudgg/video_info#102]
There is an issue in [link_thumbnailer](https://github.com/gottfrois/link_thumbnailer/issues/69#issuecomment-137073683) which origin is in the content passed [from video_info to oga gem using Kernel.open(...)](https://github.com/thibaudgg/video_info/blob/master/lib/video_info/providers/youtube_scraper.rb#L93-L95)

If anyone is interested in solving, I can provide more details.

**Comment by vheuken** [comment]
Maybe we shouldn't be using `open` at all since [it seems like a bad idea in general](http://sakurity.com/blog/2015/02/28/openuri.html)

>If anyone is interested in solving, I can provide more details.

That would certainly be helpful.

**Comment by vheuken** [comment]
I noticed that link_thumbnailer [is using 2.4](https://github.com/gottfrois/link_thumbnailer/blob/master/link_thumbnailer.gemspec#L25). 2.5 is out. Have you tried using that?

**Comment by 0mega** [comment]
@vheuken Yes it might be a good idea to get rid of open after reading that. But I'd open another issue with enhancement label for that.

For now the fix would be to change [this line](https://github.com/thibaudgg/video_info/blob/master/lib/video_info/providers/youtube_scraper.rb#L93) to be:
`video_id = url.split('/v/')[1].split('?')[0]` this will discard all unnecessary query params which make the link redirect and that seems to work here.

Now after you saying about 2.5, I tried it and yes, it actually solves the problem, don't know what changed but it works =).

Thanks

**Comment by vheuken** [comment]
That is odd. since the line you mentioned is introduced after 2.5 (it will be in 2.6). It was literally added three days ago. Were you using the master branch or something?

**Comment by vheuken** [comment]
Can you give me an example of a URL with params that cause problems?

**Comment by 0mega** [comment]
Hmm, that's strange, I was actually playing with the 2.4 which got installed along with link_thumbnailer. And then I started looking at master of video_info and installed it, that's why it worked I guess.
A little confusion with versions.

The url that fails is this one https://www.youtube.com/watch?v=Y45Zq-yKpRw. Which works fine with 2.5 btw.

**Comment by vheuken** [comment]
That URL is actually handled by line 97 in that file. The stuff you linked
to is only relevant for URLs formatted like `youtube.com/v/{VIDEO_ID}` so
it should never be an issue.

**Comment by 0mega** [comment]
It was late yesterday and I somehow made it work, but it wasn't the 2.5 that solved it, I think I might have changed the actual installed video_info gem's code.

>The stuff you linked
to is only relevant for URLs formatted like `youtube.com/v/{VIDEO_ID}` so
it should never be an issue.

It becomes an issue because of the way this URL is used in link_thumbnailer. It parses the Youtube OG data and the result of that is two URLs pointing to the video. Then it feeds those URLs to video_info and one of those URLs is http://youtube.con/v/{video_id}?some_param=x and this is the one that produces the error reported on the [link_thumbnailer issue](https://github.com/gottfrois/link_thumbnailer/issues/69).

From what I understand, the problem is that when we run [these lines](https://github.com/thibaudgg/video_info/blob/master/lib/video_info/providers/youtube_scraper.rb#L93-L94)
The resulting `video_id` will be the video id itself and some query parameters (if any). In case when query parameters are present, it will fail to parse because youtube redirects you to yet another link and this is probably not well handled.

Hence my comment on changing [this line]() to this: `video_id = url.split('/v/')[1].split('?')[0]`

*Note:* I'm trying to make this work with current master code of video_info

**Comment by vheuken** [comment]
@0mega Ah, I see. I just tested master with the URL `https://www.youtube.com/v/ylTY9WbMGDc?someParam=foo` and I saw the issue. I changed that line to the one you suggested, added a test for it, and pushed it to master. Can you try the current master code?

**Comment by 0mega** [comment]
Yes it's working =) thanks. Just a note, I think you accidentally committed _video_info-2.5.0.gem_ file.

**Comment by vheuken** [comment]
>Now it would be great to have a version bump so that link_thumbnailer can be fixed

I think we're waiting for #95, #62, #86, and #65 to be fixed before we do a version bump. I'm going to try to get that ready by this weekend.

For now, you can add this to the Gemfile to use the master branch:

`gem 'video_info', github: 'thibaudgg/video_info'`

>Just a note, I think you accidentally committed video_info-2.5.0.gem file.

Whoops! Fixed.
