### ISSUE TITLE
Issue with Vimeo Thumbnail

### ISSUE THREAD

**Issue by ttseng** [thibaudgg/video_info#107]
I saw that Vimeo now requires authentication, so I registered my app and generated an authentication token.  However, it seems like trying to get the thumbnails using something like ```VideoInfo.new(video_url).thumbnail_large``` is returning a 400 bad request.

Does this mean you can no longer grab the thumbnails using the Gem?

**Comment by vheuken** [comment]
>Does this mean you can no longer grab the thumbnails using the Gem?

No, [thumbnails should be working.](https://github.com/thibaudgg/video_info/blob/master/spec/lib/video_info/providers/vimeo_spec.rb#L146)


Can you double check to make sure the API key you provided to `VideoInfo.provider_api_keys = { vimeo: 'YOUR_API_KEY' }` is correct? I believe `400 bad request` is returned when the API key provided is invalid.

**Comment by ttseng** [comment]
I am using a generated access token for my api key.  I didn't see any parameter on vimeo titled "api key," so I wasn't sure what to use.  Should I be using something else?

**Comment by vheuken** [comment]
>Should I be using something else?

I'm actually not sure. I didn't write the Vimeo API code (that was @zdb) and I don't personally use Vimeo.

Vimeo documentation says to register your application here: https://developer.vimeo.com/apps/new  and they will then let you create a key. Have you tried that? 

If that isn't working for you, I can give it a try and see if I can better tell you where to get the key. The key should [look like this.](https://github.com/thibaudgg/video_info/blob/master/spec/lib/video_info/providers/vimeo_spec.rb#L5)

**Comment by ttseng** [comment]
Ok, I have confirmed that it should be the client identifier, which I have switched too.  This is the error I am getting when trying to retrieve a thumbnail:

MultiJson::ParseError: JSON::ParserError
	from /Users/ttseng/.rvm/gems/ruby-2.1.7/gems/multi_json-1.11.2/lib/multi_json/adapter.rb:19:in `load'
	from /Users/ttseng/.rvm/gems/ruby-2.1.7/gems/multi_json-1.11.2/lib/multi_json.rb:119:in `load'
	from /Users/ttseng/.rvm/gems/ruby-2.1.7/gems/video_info-2.5.0/lib/video_info/provider.rb:78:in `_set_data_from_api'
	from /Users/ttseng/.rvm/gems/ruby-2.1.7/gems/video_info-2.5.0/lib/video_info/provider.rb:32:in `data'
	from /Users/ttseng/.rvm/gems/ruby-2.1.7/gems/video_info-2.5.0/lib/video_info/providers/vimeo.rb:102:in `_video'
	from /Users/ttseng/.rvm/gems/ruby-2.1.7/gems/video_info-2.5.0/lib/video_info/providers/vimeo.rb:42:in `thumbnail_id'
	from /Users/ttseng/.rvm/gems/ruby-2.1.7/gems/video_info-2.5.0/lib/video_info/providers/vimeo.rb:46:in `thumbnail'
	from /Users/ttseng/.rvm/gems/ruby-2.1.7/gems/video_info-2.5.0/lib/video_info/providers/vimeo.rb:59:in `thumbnail_large'
	from (irb):4
	from /Users/ttseng/.rvm/gems/ruby-2.1.7/gems/railties-3.2.15/lib/rails/commands/console.rb:47:in `start'
	from /Users/ttseng/.rvm/gems/ruby-2.1.7/gems/railties-3.2.15/lib/rails/commands/console.rb:8:in `start'
	from /Users/ttseng/.rvm/gems/ruby-2.1.7/gems/railties-3.2.15/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
'''

Other properties (such as provider, embed_url, etc.) seem to work, so I am pretty sure this is a problem with grabbing the thumbnail in particular.

**Comment by zdb** [comment]
@ttseng 
The API token is obtained via the Authentication tab of your app.  It should be the access token that is generated like bellow.  

![image](https://cloud.githubusercontent.com/assets/1664197/9806824/ea275f92-57fe-11e5-9bdd-7ded0bdd5f97.png)

embed_url, and provider are just string interpolation using the parsed id.  They don't require an API call.    Methods like title, author, thumbnail do.

**Comment by ttseng** [comment]
Using the access token, I still get the same multijson parseerror

**Comment by zdb** [comment]
What is the url you are having problems with?

**Comment by ttseng** [comment]
this is the vimeo video: 
https://vimeo.com/markdayschool/review/108439895/b0b4dda4ef

I just saw that for other vimeo links, it works, such as https://vimeo.com/127438804

**Comment by zdb** [comment]
Yes, I was unaware that url format existed.  It must be extracting an invalid video id during the url parsing.

**Comment by ttseng** [comment]
I can't say much about the details of how the video was uploaded or shared...this is a video someone else attempted to post my Rails app and reported having issues with.

**Comment by zdb** [comment]
I am getting strange behavior via the Vimeo API.  

GET https://api.vimeo.com/videos/108439895 returns an empty 200 OK
GET https://api.vimeo.com/videos/108439895/credits returns valid results
as do the other extended urls.

**Comment by vheuken** [comment]
@zdb That's odd. Would this be something that we could work around?

**Comment by zdb** [comment]
For this specific case, I think we would have to resort to scraping the url.  I just tried the video id on the v2 api and it also has problems.

http://vimeo.com/api/v2/video/108439895.json

**Comment by vheuken** [comment]
Considering [we're already doing this in the Youtube scraper](https://github.com/thibaudgg/video_info/blob/master/lib/video_info/providers/youtube_scraper.rb#L79) I don't mind that fix very much.

Also, I recently started working on the Vimeo scraper and I noticed that there seems to be quite a few different types of video pages in Vimeo. I'm not to deep into it, but a function to extract the ID from Vimeo URLs of all types could be useful for that, too.

**Comment by zdb** [comment]
So I contacted Vimeo and they fixed the 200 response. Repsonse is now 404 with json response of {  "error": "The requested video could not be found"}.  This response is issued when the video does not exist, or the video is private and there are insufficient privileges to view it.

**Comment by vheuken** [comment]
@zdb @0mega has changed one of the Vimeo specs to use a different video URL. The diff is here: https://github.com/0mega/video_info/commit/5054492f6a02959cda4d7d1ef6c0361692469531  and his explanation is in #108

**Comment by vheuken** [comment]
Can you guys try the master branch now? Vimeo scraper should be in and we'll push a new version shortly. Sorry for the wait!

**Comment by vheuken** [comment]
Anyone know if this problem is still relevant? @zdb? @ttseng?

**Comment by vheuken** [comment]
I'm closing this issue. The relevant URLs don't seem to be valid anymore. If anyone has another example, please let me know.
