### ISSUE TITLE
compatibility with iso8601 gem version 0.9?

### ISSUE THREAD

**Issue by maia** [thibaudgg/video_info#112]
`iso8601` 0.9.0 is not compatible with previous versions, see [here](https://github.com/arnau/ISO8601/blob/master/CHANGELOG.md). You're specifying it with `~> 0.8` which should either be replaced by `0.8.7` or, in case video_info is already compatible with 0.9.x, with `~> 0.9`.

**Comment by vheuken** [comment]
Thanks for the heads up. I just upgraded to 0.9 and the tests pass on my machine. If they pass on Travis I'll close this issue. Thanks!

**Comment by vheuken** [comment]
Huh, looks like after upgrading, Travis is actually failing for an unrelated reason (looks like I should have also pinned the development dependencies).

**Comment by vheuken** [comment]
Okay, since the error was unrelated and it seems the tests run fine on my end, I'm closing this issue.
