### ISSUE TITLE
YouTube not working. 

### ISSUE THREAD

**Issue by abrambailey** [thibaudgg/video_info#113]
Here is YouTube. I was getting an error about the API key, but I've fixed that.
```ruby
2.2.1 :001 > video = VideoInfo.new("https://www.youtube.com/watch?v=mZqGqE0D0n4")
#<VideoInfo:0x007f983476d5a8 @provider=#<VideoInfo::Providers::Youtube:0x007f983476cd38 @options={"User-Agent"=>"VideoInfo/2.5.0"}, @url="https://www.youtube.com/watch?v=mZqGqE0D0n4", @video_id="mZqGqE0D0n4">>
2.2.1 :002 > video.title
nil
```
Vimeo is working fine:
```ruby
2.2.1 :003 > video = VideoInfo.new('https://vimeo.com/107231188')
#<VideoInfo:0x007f9838c15520 @provider=#<VideoInfo::Providers::Vimeo:0x007f9838c14e68 @options={"User-Agent"=>"VideoInfo/2.5.0", "Authorization"=>"bearer d329c56ca0ed186553aa9f473783e37a", "Accept"=>"application/vnd.vimeo.*+json;version=3.2"}, @url="https://vimeo.com/107231188", @video_id="107231188">>
2.2.1 :004 > video.title
"Welcome to Union Glacier"
```

**Comment by vheuken** [comment]
Did you enter a Youtube API key, or are you using the scraper (if no API key is supplied, it defaults to the scraper)?

**Comment by vheuken** [comment]
I just tested both the API and scraper and both seem to be working fine. 

Can you try the following:
1) Confirm that you are using the latest version of video_info (2.4.2) with `VideoInfo::VERSION`
2) Post what version of Ruby you are using (we only actively support 2.2.0+)
3) Try cloning the repository and running `bundle install && rspec`. 

Thanks.

**Comment by abrambailey** [comment]
Hey thanks for responding @vheuken ... Yes, I did enter the API key and I'm using 2.5.0  (I noticed that was also included in the `VideoInfo` object above). 

`ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]`

I used `gem 'video_info', git: 'https://github.com/thibaudgg/video_info.git'` in my gemfile..

**Comment by vheuken** [comment]
Huh, so you're pulling from master. Master is ahead of 2.5 by a few commits. 

Can you try just `gem 'video_info'`? You might have to uninstall the current gem (I'm not sure if RubyGems can tell the difference between 2.5 and the 2.5 in master).

**Comment by abrambailey** [comment]
Ok, I did `gem uninstall video_info`and rebundled .. still seeing the same error. Is there any way to get more verbose output ... still just seeing `nil` for `video.title` and `false` for `video.available?` ... Vimeo still working as expected.

**Comment by vheuken** [comment]
No, there is currently no way to get a more verbose output. That is something that should be fixed.

Are you sure your API key is valid? You can try cloning the repository and running the test suite, or you can go [into the spec and get the API key it uses](https://github.com/thibaudgg/video_info/blob/master/spec/lib/video_info/providers/youtube_api_spec.rb#L5) and try that.

Also, have you tried the scraper?

**Comment by abrambailey** [comment]
OK, I think I realized what the problem is. I'm testing locally and I guess I need to be whitelisted. The API key is correct and works from my server for geocoding and other APIs... I found out by using the ruby geocoder gem which presents the error `Google Geocoding API error: request denied.`

**Comment by abrambailey** [comment]
Ah, finally figured it out. My IP address changed when I changed ISPs ... Doh! Thanks for your help man.

**Comment by vheuken** [comment]
Cool. Glad you figured out your issue. Closing this.
