### ISSUE TITLE
Issue with format of youtube playlists url

### ISSUE THREAD

**Issue by g3ortega** [thibaudgg/video_info#114]
Hi, I am starting to use this gem for a recent project. It's very good, I just had a problem related to youtube urls for playlists.

When I copied/pasted a playlist, youtube gives me the following format: 
https://www.youtube.com/playlist?list=PLxg-INKFfByBR49TtCz1A9t4qCm5msNki

In the docs I find that you work with this format:
http://www.youtube.com/playlist?p=PL9hW1uS6HUftLdHI6RIsaf-iXTm09qnEr

So, when I try to use the first one I get this error:

`Url is not valid, video_id is not found: https://www.youtube.com/playlist?list=PLxg-INKFfByBR49TnCz1M9t4qCm5msNki`

The problem is fixed only changing the format, which is OK for me, but the users usually copy/paste the URLs directly from Youtube.

**Comment by vheuken** [comment]
Hi @g3ortega, 

I clicked your first link and it says "The playlist does not exist". Are you sure you got the URL right?

**Comment by vheuken** [comment]
Ah, okay. I understand your issue now. It is the `&list=`. Thanks for the report. I'll get a fix in soon.

For future reference, a proper URL to test with:
`https://www.youtube.com/playlist?list=PL9hW1uS6HUftLdHI6RIsaf-iXTm09qnEr`

**Comment by vheuken** [comment]
Fixed. Should be in the next release!

**Comment by vheuken** [comment]
Keep an eye out on: https://github.com/thibaudgg/video_info/issues/103

**Comment by g3ortega** [comment]
Thank you! Sorry for my late response. Really appreciated!
