### ISSUE TITLE
Reducing Gems Dependencies

### ISSUE THREAD

**Issue by thibaudgg** [thibaudgg/video_info#116]
Following Mike Perham post: http://www.mikeperham.com/2016/02/09/kill-your-dependencies

It could be a good idea to review our gems dependencies and maybe removing some of them.

**Comment by vheuken** [comment]
Good idea. Just taking a quick look, we should be able to drop `multi_json` pretty easily. I'll take a deeper look soon.

**Comment by thibaudgg** [comment]
Great, thanks @vheuken

**Comment by vheuken** [comment]
- [ ] multi_json
- [ ] htmlentities
- [ ] addressable
- [ ] iso8601
- [x] ~~oga~~ Keeping. Definitely need it for the scrapers 
- [ ] open_uri_redirections
- [ ] net_http_timeout_errors

**Comment by thibaudgg** [comment]
:heart_eyes:

**Comment by vheuken** [comment]
So now we have three gems: `iso8601`, `oga`, and `net_http_timeout_errors`. Woo!

I'm was going to handle PR #83 soon. Maybe after that we'll be ready for a new release, unless you have anything else in mind. I'd also like to confirm whether or not #107 is still an issue.

**Comment by thibaudgg** [comment]
Awesome thanks! Ping me when you need to release a new version, I'll give you the right on rubygems.
