### ISSUE TITLE
Handle some hound-ci/rubocop things

### ISSUE THREAD

**Issue by vheuken** [thibaudgg/video_info#117]
Since I've started working on this, there have been several issues involving Hound-CI that make contributing a bit confusing. For example:
* I think we've established that we don't care about line length when it comes to string literals
* In the specs, we use double-quoted strings a lot when we don't need them. I find this acceptable because this seems to be common practice with RSpec and it is what is shown in examples, but Hound-CI still counts them as errors.
* Hound-CI seems to be using Rubocop, however we are not encouraging Rubocop usage before committing, causing inevitable "Fixing Hound warnings.." commits whenever we get PRs.

I think we should fix these issues in the Rubocop config. I'm not familiar with Rubocop, but I imagine it would be pretty simple.

I also think it would be a good idea to have a `Contributing` section of the README (or a page in the Wiki) saying exactly what style guide we follow and encouraging people to run Rubocop on the codebase before committing.

**Comment by thibaudgg** [comment]
Good point, we should advertise our Rubocop config and usage. We're using the [Hound-CI default](https://raw.githubusercontent.com/houndci/hound/master/config/style_guides/ruby.yml) documented here: https://houndci.com/configuration#ruby.

:+1:

**Comment by vheuken** [comment]
Cool, thanks for pointing that out. I'll handle this as soon as I can. I'll also run through the codebase and see if any style issues fell through the cracks.

**Comment by thibaudgg** [comment]
Perfect :ok_hand:

**Comment by vheuken** [comment]
@thibaudgg I made a branch where I set the rubocop config to use hound-ci's rubocop config. The issue is that Hound-CI's default is to prefer double quote for string literals. However, this was overridden by your rubocop config, which contained:

```
StringLiterals:
  EnforcedStyle: single_quotes
```

Are you okay with preserving that? Else we'd need to go through and change a bunch of single quotes to double quotes, which would be easy enough, but annoying. I'd vote on preserving it personally.

**Comment by vheuken** [comment]
#122 Fixed all rubocop warnings in the provider source files. I'll go ahead and do the remaining files some other time. We'll also need to add documentation, which I'll handle when I fix the remaining warnings.

**Comment by thibaudgg** [comment]
I'm personally in the `single_quotes` camp side as well, so let's keep it that way. :+1:

**Comment by vheuken** [comment]
Went ahead and cleaned up the rest of lib/. Now we're totally clean on that front. I've decided to go ahead and do the stuff in spec/, too. That way we should be able to only accept PRs that completely pass the linter. Much neater that way. I'm hoping to get to that and the rest of the issues this weekend.

For what it's worth, we also definitely ended up with cleaner code because of it!

**Comment by thibaudgg** [comment]
Yup, big fan of Rubocop!

**Comment by vheuken** [comment]
Went from 357 errors down to 162 in PR #129. Hopefully I can get to the rest this weekend!

**Comment by vheuken** [comment]
Now running Rubocop brings up 0 errors! Let's keep it that way!

**Comment by thibaudgg** [comment]
:+1:
