### ISSUE TITLE
Add a changelog for 2.6

### ISSUE THREAD

**Issue by vheuken** [thibaudgg/video_info#118]
Currently we have no real Changelog. A simple changelog would be a nice addition, especially since this is a reasonably popular gem. We can start with 2.5 -> 2.6 pretty easily and continue from there.

**Comment by thibaudgg** [comment]
This is our changelog: https://github.com/thibaudgg/video_info/releases
Forget adding details about 2.6 :fearful:!

**Comment by vheuken** [comment]
Whoops! I wasn't aware. Thanks for letting me know! As far as I know, all the relevant 2.6 things are listed in #103. Changing the title.

**Comment by thibaudgg** [comment]
Great could you edit it then? https://github.com/thibaudgg/video_info/releases/edit/v2.6.0
Thanks!

**Comment by vheuken** [comment]
Done! https://github.com/thibaudgg/video_info/releases/tag/v2.6.0

**Comment by thibaudgg** [comment]
:+1:
