### ISSUE TITLE
Add author fields to services which currently don't have them implemented

### ISSUE THREAD

**Issue by vheuken** [thibaudgg/video_info#119]
This has been partially done in PR #83, but it isn't complete and a rebase would be a big hassle.

The three fields in question:
* Author Thumbnail
* Author Name
* Author Domain

**Comment by vheuken** [comment]
Keeping a changelog here of what I've implemented:
`#author`: YoutubeAPI

**Comment by vheuken** [comment]
So I'm having a really strange issue with `#author_url`. I keep getting:

```
     NoMethodError:
       undefined method `author_url' for #<VideoInfo:0x00000004789890>
       Did you mean?  author
```

You can see the spec [here](https://github.com/vheuken/video_info/blob/author/spec/lib/video_info/providers/youtube_spec.rb#L240) and you can see the partial implementation [here](https://github.com/vheuken/video_info/blob/author/lib/video_info/providers/youtube_scraper.rb#L22) .....I can't for the life of me figure out why it is causing issues though. I've tried changing the name, deleting other methods/specs, and doing it for the API, but it is always the same issue.  I've also tried on both Ruby 2.2.4 and Ruby 2.3.0. If you have any ideas, I'd love to hear them.

**Comment by vheuken** [comment]
Also for what it's worth, I put `#author` and `#author_thumbnail` for Youtube in master and have updated the documentation accordingly.

**Comment by vheuken** [comment]
Found the issue. I needed to add `:author_url` [here](https://github.com/thibaudgg/video_info/blob/893446010dd1e909619b672793fb8132e7d578d5/lib/video_info.rb#L57)

Good to know!

**Comment by vheuken** [comment]
I believe now it just needs to be implemented for Wistia, Vimeo, DailyMotion, Vkontakte, and possibly YoutubePlaylist. I'll hopefully get to these and the rest of the issues this weekend.

**Comment by thibaudgg** [comment]
Ok great, glad that you figure it out! What do you think about making pull request for that kind of feature improvement, committing directly on master for small changes/fixes is fine, but for feature addition the require multiple commits I think PR are a better fit. It allows us to review them more properly as well.

Thanks!

**Comment by vheuken** [comment]
Good idea. I was actually originally intending to do everything in a branch and then just manually merge it into master myself, but I got a bit overzealous with my merging. PR definitely sounds like a better workflow for this.

**Comment by vheuken** [comment]
Sent in PR #124 for Vimeo. Still need to handle Wistia, Vimeo, DailyMotion, and Vkontakte.

**Comment by vheuken** [comment]
It looks like the concept of an "author" is not really a thing on Wistia, so it's just Vkontakte, DailyMotion, and possible YoutubePlaylist

**Comment by vheuken** [comment]
I implemented #author_url and #author in Dailymotion without much trouble at all. However, it looks like there is no way to get the author thumbnail via the API. Should we resort to page scraping for that?

**Comment by vheuken** [comment]
Looks like all that is left is YoutubePlaylist. I'm not even sure if this is applicable to that, but we'll see!

**Comment by vheuken** [comment]
Completed now that #127 is merged in.
