### ISSUE TITLE
Merge API/Scraper specs

### ISSUE THREAD

**Issue by vheuken** [thibaudgg/video_info#120]
Right now the specs for the API and Scrapers are two different files. The actual specs are virtually identical save for a couple differences. It would be a huge maintenance plus if we could merge them into one.

**Comment by thibaudgg** [comment]
Good point, maybe some shared example could help: https://www.relishapp.com/rspec/rspec-core/docs/example-groups/shared-examples

**Comment by vheuken** [comment]
I think I have a solution for this. Just gotta clean it up a bit. I'll let you look at it via PR to okay it. (For what it's worth, I think it's quite elegant)

**Comment by vheuken** [comment]
Handled in PRs #138, #137, and #136
