### ISSUE TITLE
Add "Features" section to README

### ISSUE THREAD

**Issue by vheuken** [thibaudgg/video_info#121]
Right now, the only way to see what information the library provides is to look through the code examples. I think a list of bullet points on what information it provides (title, author, thumbnail, etc) at the top of the README would be nice for people just finding the gem.

Going to wait for #83 to get done so we have a more uniform set of features across providers.

**Comment by thibaudgg** [comment]
:+1:

**Comment by vheuken** [comment]
Done. Check it out in master.
