### ISSUE TITLE
Replacing Travis-CI

### ISSUE THREAD

**Issue by vheuken** [thibaudgg/video_info#123]
So, on Travis-CI, we've been getting frequent-but sporadic 500 errors with APIs and 429 errors with scrapers. I'm starting to think this is an unavoidable issue due to the nature of our tests.

I think a good option would be to roll my own CI system on a VPS (I have a couple so it's no big deal for me, plus I enjoy doing servery stuff). This will also allow us to run nightly builds, which would be nice because of the scrapers potentially breaking. There is essentially zero risk for you, @thibaudgg, since we can still have Travis run in the background and fall back to it if I ever go AWOL.

**Comment by thibaudgg** [comment]
These HTTP errors are pretty annoying, we could give a try to [rspec-retry](https://github.com/NoRedInk/rspec-retry) on Travis.

**Comment by vheuken** [comment]
We could try, but with the frequency of the issues I don't think it will help. My best guess is that there are a ton of other people making API calls and pulling pages from sites like Vimeo/Youtube and it triggered some flag in their systems. I'm not sure if you remember, but the original reason we didn't switch over to the new Travis infrastructure was because the Youtube scraper would fail because we'd get sent to a page where we need to enter a captcha to prove we aren't just a bot.

**Comment by thibaudgg** [comment]
@vheuken I see, we should maybe then store VCR cassettes in our git repo and use the [Automatic Re-recording](https://relishapp.com/vcr/vcr/v/3-0-1/docs/cassettes/automatic-re-recording) feature.

**Comment by vheuken** [comment]
Well, we do have the infrastructure setup for that, so that sounds like the best option. I *really* don't like having all of those fixtures constantly getting committed, but if it is the best way to handle it, then I guess it needs to be done.

**Comment by vheuken** [comment]
Yeah, adding the fixtures back into the repo seems to have solved the problem. It's kinda annoying that we have to deal with a ton of meta files being added/removed every week, but I guess it's the best solution.

Also, @thibaudgg what would you say to taking JRuby and Rubinous out of "allowed failures"? To the best of my knowledge they are both 2.2+ compliant and we have no problems unique to them.

**Comment by thibaudgg** [comment]
> Yeah, adding the fixtures back into the repo seems to have solved the problem. It's kinda annoying that we have to deal with a ton of meta files being added/removed every week, but I guess it's the best solution.

Yes that's not ideal but that the price to pay, I guess we can still re-recording every 1 week.

> Also, @thibaudgg what would you say to taking JRuby and Rubinous out of "allowed failures"? To the best of my knowledge they are both 2.2+ compliant and we have no problems unique to them.

Sure, if they're passing reliably I've no objections.
