### ISSUE TITLE
#keywords API inconsistency

### ISSUE THREAD

**Issue by vheuken** [thibaudgg/video_info#131]
I noticed while cleaning up the specs that the return type for `#keywords` is inconsistent across different providers.

```ruby
2.3.0 :009 > vimeo_video.keywords
 => "cherry bloom, secret sounds, king of the knife, rock, alternative" 
2.3.0 :010 > youtube_video.keywords
 => ["cherry", "bloom", "king", "of", "the", "knife", "guitar", "drum", "clip", "rock", "alternative", "tremplin", "Paris-Forum"] 
```

Youtube returns an Array, Vimeo returns a string. I think the standard behavior should be Array.

Obviously, fixing this would be a breaking change, so we'd need to bump the version to `3.0.0` (which would also be fitting, since getting #130 in would be a pretty big feature).

It also looks like Vkontakte has a similar issue, where the "keywords" are just the descripotion. @drakmail  Would you say it is fair to parse the description into an array of words and use that as `Vkontakte#keywords`?

**Comment by thibaudgg** [comment]
Go for arrays everywhere! :+1:

**Comment by vheuken** [comment]
PR #133 Handles the Vimeo part of it. Waiting on @drakmail to see how to best approach the Vkontakte side where '#keywords' seems to just be the description.

**Comment by vheuken** [comment]
I decided to make `Vkontakte#keywords` return nil since there are no real "keywords" in Vkonakte videos as far as I can tell. This should also allow us to add a different implementation in without having to consider it a breaking change. If anyone thinks this approach isn't good, let me know.
