### ISSUE TITLE
Minor thing regarding Travis-CI and code coverage reporting

### ISSUE THREAD

**Issue by vheuken** [thibaudgg/video_info#146]
I noticed that the Code Coverage seems to have went down rather significantly for some reason. It appears to be reported via Travis-CI. I noticed in PR #145  that coverage went up to 100% at least once.

 I looked into it:

Ruby 2.3 and 2.2.4 both report "Coverage is at 100.0%."
JRuby reports "Coverage is at 0.0%."
Rubinous reports "Coverage is at 87.78%."

I get the impression that Coveralls doesn't play too nicely with JRuby/Rubinous. I also think that whichever Travis-CI build ends up completing last ends up submitting the report, since Rubinous seems to usually finish last and the current coverage seems to reflect the Rubinous coverage.

Perhaps we should set an environment variable so that coverage is only reported for the latest official Ruby implementation version? It might not be worth it and we can just keep it the way it is, though we run the risk of JRuby running last (not unlikely since JVM is slow to start) and then having the coverage reported as 0%, which would look bad on our Github page.

If you feel this is too minor to bother with, feel free to close this.

**Comment by drakmail** [comment]
As can I see at this moment there is a 100% code coverage

**Comment by vheuken** [comment]
Yeah, it looks like it's reporting 100% now and has been consistently for awhile. Closing this.
