### ISSUE TITLE
YouTube Live Video Status

### ISSUE THREAD

**Issue by Brotakuu** [thibaudgg/video_info#151]
With the growing popularity of YouTube live and its compatibility with this `video_info` (Live videos have the same url format and the gem is already compatible with live videos), it would be useful to add the Live video status.

I added the api method `live_broadcast_content` which returns `none`, `live`, or `upcoming` (or `nil` for invalid or unavailable videos).

API Docs: 
    https://developers.google.com/youtube/v3/docs/videos#properties

Here's the fork for anyone else working with live videos. 
https://github.com/Brotakuu/video_info

Note: this only works with the API.

**Comment by vheuken** [comment]
>Pull request for anyone else working with live videos

Was this supposed to be a pull request?

>I added the api method live_broadcast_content which returns none, live, or upcoming (or nil for invalid or unavailable videos).

I understand that this is how the Youtube API names it, but I don't think mimicking the API is the right choice here. We might add other providers with live broadcasted content (like Facebook currently has).   Perhaps just `.live?`, `.live_broadcast?`, or `.is_live?`  would work better.

**Comment by Brotakuu** [comment]
Good point. Changed it to ".live_stream" to avoid any confusion with the video being available/unavailable.

I was unable to push a new branch, so I created a fork:
https://github.com/Brotakuu/video_info

**Comment by vheuken** [comment]
I was actually thinking more along the lines of a function that returns a boolean along with a function called `.live_status` or something that returns a symbol (`:live`, `:upcoming`, `:ended`) or `nil` if it isn't a live stream.

That being said, a bit more discussion should be had before this feature gets implemented. We should look into how Facebook handles it so we can have a consistent API between them.

Looking at the [Facebook Video API docs](https://developers.facebook.com/docs/graph-api/reference/video), there is a `live_status` enum, but it doesn't list the potential values in the documentation. We should find out what that returns before deciding on the exact implementation.

**Comment by Brotakuu** [comment]
Makes sense to look into Facebook video and implement a consistent API across multiple platforms.
 
Btw, do you have any suggestions for running tests on live videos? Since there's no way to consistently test against `:live` or `:upcoming`.

**Comment by vheuken** [comment]
I do not, but I'm sure there's a library to mock API calls or something. We'd need to look into it.

I made a separate issue for this (#152) with some of the stuff we talked about here summed up.
