### ISSUE TITLE
Release 2.6.1

### ISSUE THREAD

**Issue by drakmail** [thibaudgg/video_info#154]
Does it's possible to release 2.6.1 with fixes for vkontakte scraper?

**Comment by thibaudgg** [comment]
@vheuken I just added you as an owner on rubygems, feel free to release a new version. 👏

**Comment by vheuken** [comment]
Thanks. I'm going to do that tonight after I fix the Vimeo stuff.

**Comment by vheuken** [comment]
Fixed the Vimeo issues (they were just issues with the spec). Once Travis passes I'll bump the version and push it!

**Comment by vheuken** [comment]
@drakmail 2.6.1 is pushed! 

Rubinous fails on Travis, but that's just because of a Travis issue...I think I'm going to put JRuby and Rubinous back into `allowed_failures` as they are far too fragile.

**Comment by thibaudgg** [comment]
@vheuken 👍
