### ISSUE TITLE
NoMethodError: undefined method `css' for nil:NilClass

### ISSUE THREAD

**Issue by scepion1d** [thibaudgg/video_info#155]
I've tried to get thumbnail of video from Vimeo but receive this error. It happens if video doesn't exist. As example you could try vimeo example from README.md.

**Comment by vheuken** [comment]
Thanks for the report. I'll have a look at the issue this weekend.

**Comment by vheuken** [comment]
Fixed in master. Now if the video does not exist, the scraper will return `nil` for all info.
