### ISSUE TITLE
unexpected network error

### ISSUE THREAD

**Issue by opetznick** [thibaudgg/video_info#156]
hey there

tried to scrape a youtube video on my local machine and it worked perfectly. tried the same on the production environment (ubuntu server, same ruby version) and it throws an unexpected network error.

```
VideoInfo.new("https://www.youtube.com/watch?v=5TvkLlKutfM").title
VideoInfo::HttpError: unexpected network error while fetching information about the video
```

any ideas?

thanks in advance

**Comment by vheuken** [comment]
Interesting.

Are you using the scraper or the API? If you didn't provide an API key, you're using the scraper.

Also, what Ruby version are you running?

**Comment by opetznick** [comment]
without apikey so using the scraper. ruby version 2.3. firewall should be no issue. any idea on debugging this?

**Comment by vheuken** [comment]
We actually had a similar issue with Travis-CI before errors were implemented. Youtube decided to block Travis servers from scraping their pages and redirect it to a page with a Captcha.

Can you try this on the problematic server:
`wget https://www.youtube.com/watch?v=5TvkLlKutfM`

Examine the contents. You should be able to find the video title, view count, etc. If Youtube is blocking your server you'll get a page with a Captcha or something.

**Comment by opetznick** [comment]
this is really weird:

```
deploy@app-01:~$ wget https://www.youtube.com/watch?v=5TvkLlKutfM
--2016-05-31 03:24:12--  https://www.youtube.com/watch?v=5TvkLlKutfM
Resolving www.youtube.com (www.youtube.com)... 2a00:1450:4001:815::200e, 216.58.208.46
Connecting to www.youtube.com (www.youtube.com)|2a00:1450:4001:815::200e|:443... connected.
HTTP request sent, awaiting response... 429 Too Many Requests
2016-05-31 03:24:12 ERROR 429: Too Many Requests.
```

**Comment by vheuken** [comment]
Okay, so it isn't an issue with video_info, but with your server provider. It was most likely caused by another customer making too many requests.

My suggestion would be to get an API key. It should work with that. You can follow the instructions here: https://developers.google.com/youtube/registering_an_application
