### ISSUE TITLE
Url is not usable by any Providers

### ISSUE THREAD

**Issue by bengalamx** [thibaudgg/video_info#157]
A raise error is too much when an invalid url is provided. Can we just get nil instead?

**Comment by vheuken** [comment]
I was actually thinking about this not too long ago. While an error might seem like overkill, nil doesn't provide any information as to what was wrong.

For example, if I do `VideoInfo.new('hh')`, I get `VideoInfo::UrlError: Url is not usable by any Providers: hh`

If I do `VideoInfo.new('https://www.youtube.com/watch?v=FOO')`, I get `VideoInfo::UrlError: Url is not valid, video_id is not found`

I was thinking about maybe including a helper function. Something like `VideoInfo.valid_url?(url)` to check whether a URL is good before entering it. Then we can keep the error about no usable providers and maybe return `nil` if the video_id is not found.

**Comment by vheuken** [comment]
That being said, it's pretty idiomatic to throw an error for a bad URL. I understand that unlike, say, `net/http`, `video_info` is going to mostly be used to handle input from end users. 

May I suggest that, if you want nil on bad video URLs, just wrapping it yourself? For example:

```ruby
def get_video_info(url)
  begin
    VideoInfo.new(url)
  rescue VideoInfo::UrlError
    nil
  end
end
```

**Comment by bengalamx** [comment]
Yes that first helper would be great! But if it is too much for now, `info = VideoInfo.new(video)` should return nil, for doing something like `info.embed_code if info?` at least return empty html instead the embeded html

**Comment by vheuken** [comment]
See my above comment. It is pretty trivial to wrap `VideoInfo.new` into a function that returns `nil` when passed an invalid URL.

**Comment by bengalamx** [comment]
That works very well
```
def video_frame
	begin
		VideoInfo.new(video).embed_code
	rescue VideoInfo::UrlError
		nil
	end
end
```
Thanks @vheuken
