### ISSUE TITLE
Helper function to check validity of a URL

### ISSUE THREAD

**Issue by vheuken** [thibaudgg/video_info#158]
Since we have all the regex already, it would be nice to have a helper function to check if a URL is a valid video URL. Something like `VideoInfo.valid_url?(url)` that checks against all of the providers' URL regex.

**Comment by virtualflo** [comment]
i recommand to use the  rescue StandardError=>e (http://ruby.bastardsbook.com/chapters/exception-handling/). It's allow you to execute a specific code if you have an error. 

For example here my code: 
     
```
      begin
      video_info = VideoInfo.new(url)

      # if the url is invalid for VideoInfo
      rescue StandardError=>e
      params[:videoinfo_url] = nil

      # if the url is valid for VideoInfo
      else
        @url_status = video_info.available?
      end
```

**Comment by markets** [comment]
That would be really 👌🏼 useful! Using `rescue` for control flow is not ideal. 

I'm currently using an early return:

```ruby
return unless url.match?(/youtube\.com|youtu\.be|vimeo\.com|dailymotion\.com/)
```

But a helper from the gem `VideoInfo.valid_url?(url)` would be very appreciated :))

**Comment by thibaudgg** [comment]
@markets please feel free to open a pull request.

**Comment by markets** [comment]
@thibaudgg Just pushed a pull request #208 🙌🏼
