### ISSUE TITLE
Vimeo considered available while "This video does not exist"

### ISSUE THREAD

**Issue by clairezed** [thibaudgg/video_info#161]
Hello,

May there be a problem with vimeo availability detection ? 
I've just been scrapping this link : https://player.vimeo.com/video/2847064, and VideoInfo detects it as available while it isn't anymore. 

Do you think about a workaround ?

 VideoInfo::VERSION : "2.6.1"
ruby 2.3.0

**Comment by clairezed** [comment]
Hm, it may be strangely a problem with the vimeo token we're using. There's no more problem when using other credentials.

**Comment by vheuken** [comment]
That's interesting. You said you were using the scraper or a different API key?
