### ISSUE TITLE
Add author fields to services which currently don't have them implemented 

### ISSUE THREAD

**Issue by stefan694** [thibaudgg/video_info#162]
Hi, I see that you closed this issue https://github.com/thibaudgg/video_info/issues/119 on march 10th  : 

 It seems that it is still not working with DailyMotion.

**Comment by vheuken** [comment]
You are correct. I'll have a look at getting this implemented tomorrow. Thanks for the report!

**Comment by vheuken** [comment]
Fixed in master. To use it before the next version is released, add this line to your Gemfile:

`gem 'video_info', git: 'https://github.com/thibaudgg/video_info.git'`
