### ISSUE TITLE
Add new version

### ISSUE THREAD

**Issue by j-arnaiz** [thibaudgg/video_info#166]
Hello,

Please add new version with thumbnail_maxres PR.

Thank you.

**Comment by vheuken** [comment]
Hi @j-arnaiz 

I was planning on waiting until #130 and #152 were completed to release a new version, but I've been very busy the past few months and I haven't had a chance to. 

That being said, I think it would be acceptable to release a new version soon once #160 and #162 are done. I'm sure those can be completed soon.

Until then, you can simply put this in your Gemfile: 
`gem 'video_info', git: 'https://github.com/thibaudgg/video_info.git'`

**Comment by vheuken** [comment]
I'm closing this because there is already an issue about this.
