### ISSUE TITLE
Is there a way to check if the link is valid?

### ISSUE THREAD

**Issue by nageune** [thibaudgg/video_info#168]
I know I can check if the video is available.
I have the block
`if VideoInfo.new(link).available?
blablabla
end
`
But I still get an error if the link is is not an actual video link.
is there a way to go about this?
Or am I restricted to use the rails check if the input is indeed a link like:
`if url =~ URI::regexp
    # Correct URL
end`

Thanks

**Comment by nageune** [comment]
Just saw this feature is already being considered.

**Comment by vheuken** [comment]
It is planned for 3.0, but is not currently implemented.
