### ISSUE TITLE
YouTube Avaible Status

### ISSUE THREAD

**Issue by caiotarifa** [thibaudgg/video_info#174]
Hi.

I am having a strange problem with a YouTube video that is unavailable, but the `avaible` method is returning as true.

I noticed in the method's code **returns true to any status unless it is `rejected`**.

Looking at the [YouTube documentation](https://developers.google.com/youtube/v3/docs/videos), I think other status should be considered, like `deleted` and `failed`.

Regards,
Caio Tarifa

**Comment by vheuken** [comment]
Hi @caiotarifa, 

Thanks for the report. I have a few questions:
1) Can you link me to the video in question?
2) Are you using the scraper or the API? If you didn't provide an API key, you're using the scraper.
3) What version of Ruby are you running?

**Comment by vheuken** [comment]
As for other statuses, I agree. I think `available?` should remain boolean, but I'd defiantly consider another method for more details. Perhaps called `status` or something.

**Comment by caiotarifa** [comment]
I agree @vheuken, but `deleted` and `failed` should return `false` and not `true`.

**Comment by vheuken** [comment]
@caiotarifa I agree. Can you link me to the video in question? It'd make it easier to have a URL on hand for when I try to fix it tonight.

And so I'm clear, you are using the API, not the scraper, right?

**Comment by vheuken** [comment]
@caiotarifa I have tried the following videos:

https://www.youtube.com/watch?v=IjVZ-_d1DHU
https://www.youtube.com/watch?v=M0kXknv0y6Q
https://www.youtube.com/watch?v=voO37qwmLkg

All three seem to be unavailable for different reasons, and `available?` returns `false` for all of them. Please link me to the video you are having issue with.

**Comment by caiotarifa** [comment]
Hi, @vheuken.

I am sorry, I was trying with an **embed URL**.

(Maybe it could be a feature? 😄 )

**Comment by vheuken** [comment]
I'll think about that. That could be a good idea. I'm closing this issue, though.
