### ISSUE TITLE
How can get likes and comments and uploaded_at for youtube video?

### ISSUE THREAD

**Issue by lionel218** [thibaudgg/video_info#179]

**Comment by vheuken** [comment]
@lionel218  I know you closed this, but currently you cannot get comments and likes.

You should be able to get `uploaded_at` from `#date`

**Comment by lionel218** [comment]
Hi @vheuken, Thanks for your kind response.
I've just fixed to get the statistics data using video.data['items'][0]['statistics']

Thanks
