### ISSUE TITLE
NoMethodError with Youtube Scraper when the video has no description

### ISSUE THREAD

**Issue by Spone** [thibaudgg/video_info#180]
```
$ video = VideoInfo.new("https://www.youtube.com/watch?v=WVsj2pS-zFY")
=> #<VideoInfo:0x00007ff674bbca20 @provider=#<VideoInfo::Providers::Youtube:0x00007ff674bafd98 @options={"User-Agent"=>"VideoInfo/2.7"}, @url="https://www.youtube.com/watch?v=WVsj2pS-zFY", @video_id="WVsj2pS-zFY">>
$ video.description
NoMethodError (undefined method `value' for nil:NilClass)
```

I expect `video.description` to return `nil` when no description is found, instead of raising `NoMethodError`.

I think this is the line where it should be fixed: https://github.com/thibaudgg/video_info/blob/master/lib/video_info/providers/youtube_scraper.rb#L67

**Comment by thibaudgg** [comment]
Hi @Spone, thanks for the opening this issue. Could you please open a pull request with a fix, I'll review it quickly.
