### ISSUE TITLE
How do you access the width of youtube thumbnails?

### ISSUE THREAD

**Issue by abrambailey** [thibaudgg/video_info#182]
The width per video thumbnail is returned in the hash as follows:
```
          "thumbnails"=>
           {"default"=>
             {"url"=>"https://i.ytimg.com/vi/b4ZnvU3QkRM/default.jpg",
              "width"=>120,
              "height"=>90},
```
However, these seems to be no method to get the width, say for example `video.thumbnail_small.width`

**Comment by vheuken** [comment]
@abrambailey That currently is not supported by the API. I can add this as a feature request, though I don't know when I'll have time to implement it.

**Comment by abrambailey** [comment]
Unfortunately we had to move to using the youtube api directly so we could get the proportions out, but definitely would be a great thing to have for your gem :)
