### ISSUE TITLE
Warnings in 2.5.1

### ISSUE THREAD

**Issue by asiniy** [thibaudgg/video_info#183]
If you're using this gem on ruby 2.5.1, you should get this warning

```
/home/serge/projects/web_punch/app/controllers/videos_controller.rb:7: warning: VideoInfo#available? at /home/serge/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/forwardable.rb:157 forwarding to private metho
d VideoInfo::Providers::Youtube#available?
```

How could it be avoided?

**Comment by markets** [comment]
@asiniy is this still present in recent versions? Ruby 2.5 is EOL and officially not supported anymore in our CI.

**Comment by markets** [comment]
Closing for now as we are not officially supporting Ruby 2.5. Please, re-open if you can reproduce it in newer versions.
