### ISSUE TITLE
Instagram support

### ISSUE THREAD

**Issue by Spone** [thibaudgg/video_info#185]
Instagram is also hosting videos, it would be great to support scraping them with `video_info` :)

It's pretty easy to do because the source code for a video page, such as https://www.instagram.com/p/BurC0_eFmS4/, contains all the data as JSON (search for `window._sharedData`)

**Comment by thibaudgg** [comment]
Hey @Spone, sure thing, feel free to submit a pull request to add Instagram support.

**Comment by markets** [comment]
Hi @Spone 👋🏼 

Do you think this is still as easy as you proposed?

**Comment by Spone** [comment]
The problem is Instagram now has anti-scraping protection, you get blocked very quick.

I don't have much interest in working on that.
Feel free to close the issue.
