### ISSUE TITLE
Update oga gem dependency to version 3.0

### ISSUE THREAD

**Issue by pollinoco** [thibaudgg/video_info#186]
Oga gem release 2.16, 2.17 was removed. "For the reason why that version was removed, see issue [#196 (closed)](https://gitlab.com/yorickpeterse/oga/issues/196). You should be able to update to v3.0 with no fear in most cases."

**Comment by thibaudgg** [comment]
Hi @pollinoco,

I'm no more actively maintaining that gem, but if you prepare a pull request with the Oga gem upgrade, I will happily merge it and release a new version.

**Comment by schugabe** [comment]
It would be great if you could release an update of this gem to fix the dependency issue.

**Comment by thibaudgg** [comment]
I just published the version 2.7.1 with Oga 3 support.

Thanks @andrewkendall for the fix.

Closed by #187
