### ISSUE TITLE
Exposing more video statistics 

### ISSUE THREAD

**Issue by ishields** [thibaudgg/video_info#188]
Would it make sense to expose more statistics so they can be used when available?
The YouTube api returns a lot more useful statistics than what is available via the model (because the _video_statistics attribute is private).

```
 {"viewCount"=>"1036033", "likeCount"=>"27742", "dislikeCount"=>"1160", "favoriteCount"=>"0", "commentCount"=>"1134"}
```

Either these raw statistics could be available as a hash or as separate methods.  Any thoughts?

**Comment by thibaudgg** [comment]
That sounds good to add, please feel free to open a pull request.

**Comment by ishields** [comment]
Do you have a preference on whether to just expose "video_stats" or do individual methods for each statistic type?

**Comment by thibaudgg** [comment]
I think `video_stats` should be enough to expose.

**Comment by markets** [comment]
@ishields I just send a PR 👉🏼 #220
