### ISSUE TITLE
Calling author_url twice errors out

### ISSUE THREAD

**Issue by ishields** [thibaudgg/video_info#189]
It appears that when using the YouTube api, calling author_url twice in a row causes an error.

This is very easily reproduced with:

```
video_info = VideoInfo.new("https://www.youtube.com/watch?v=...")
video_info.author_url => valid authors url
video_info.author_url => undefined method `[]' for nil:NilClass
```

**Comment by thibaudgg** [comment]
That sounds like a bug, could you please submit a fix?

**Comment by ishields** [comment]
Fix submitted https://github.com/thibaudgg/video_info/pull/190/files
