### ISSUE TITLE
YouTube provider does not fetch standard

### ISSUE THREAD

**Issue by ishields** [thibaudgg/video_info#191]
The thumbnail_large method for the YouTube provider returns an image who's size is only 480x360
ex: https://i.ytimg.com/vi/cDmyGzFHMsE/hqdefault.jpg

The YouTube api returns an additional size of image that isn't accssible.  
ex standard: https://i.ytimg.com/vi/cDmyGzFHMsE/sddefault.jpg

I think we need to add an additional thumbnail size.  

thumbnail_large_2x

For other providers I will simply return the large thumbnail.

**Comment by ishields** [comment]
I was mistaken. The only one missing is standard.

**Comment by thibaudgg** [comment]
Sure, I think that would be good to add, PR always appreciated 👍

**Comment by ishields** [comment]
Is the plan to make a release for these two most recent fixes?

**Comment by thibaudgg** [comment]
I have just released version 2.8, thanks for your help.
