### ISSUE TITLE
Improve performance of usable? helper

### ISSUE THREAD

**Issue by markets** [thibaudgg/video_info#209]
All providers define this method:

```ruby
def self.usable?(url)
  url ~= /PROVIDER_REGEX/
end
```

Since we don't need _matches_ and it's defined as a _predicate method_, I think we should switch to `String#match?` or `Regexp#match?` in those methods for speed (https://github.com/fastruby/fast-ruby#stringmatch-vs-stringmatch-vs-stringstart_withstringend_with-code-start-code-end):

```ruby
def self.usable?(url)
  url.match? /PROVIDER_REGEX/
end
```

What do you think @thibaudgg?

**Comment by thibaudgg** [comment]
Sure thing, please feel free to open a PR. 👍🏻

**Comment by markets** [comment]
@thibaudgg here you go 👉🏼 #210

(We should fix the build someday 🙏🏼, now it complicates contributing to this project... I'll take this task, but unfortunately I have no experience with VCR 😅)

**Comment by thibaudgg** [comment]
Yeah, the main issue is [that VCR is configured](https://github.com/thibaudgg/video_info/blob/master/spec/spec_helper.rb#L15) to re-record the cassette (request mock) after a specified amount of time. Here it seems that most provider slightly changed their response so a lot of specs must be fixed. This is certainly a good opportunity to improve the specs base. It would be great if you can look at it, I can assist if you have some questions about VCR.

**Comment by markets** [comment]
Hey @thibaudgg 👋🏼 if you (or somebody that implemented this part) can fix 1 provider as an example, I'll finish the job! That would be super helpful 🤝 

Thanks!
