### ISSUE TITLE
valid_url returns true with user page

### ISSUE THREAD

**Issue by miguelpeniche** [thibaudgg/video_info#223]
There is a minor bug, checking the Vimeo user page `VideoInfo.valid_url? "https://vimeo.com/user123456789"` is returning `true`.

**Comment by markets** [comment]
Hello @miguelpeniche!

This URL is checked by this method:

https://github.com/thibaudgg/video_info/blob/5fb0edff2bfeccb1ae297db741d01199837f1be5/lib/video_info/providers/vimeo.rb#L18

Feel free to send a patch to improve this scenario.

**Comment by Spone** [comment]
Here is a PR for this: #228
