### ISSUE TITLE
Support for Youtube Shorts

### ISSUE THREAD

**Issue by Spone** [thibaudgg/video_info#229]
I think video_info can be modified to support Youtube Shorts. Here is an example URL https://www.youtube.com/shorts/Yk_pbPorWKg that can be transformed into the standard URL format https://www.youtube.com/watch?v=Yk_pbPorWKg in order to retrieve the video info.

@thibaudgg how would you suggest approaching this?

**Comment by thibaudgg** [comment]
@Spone sure that shouldn't be an issue. A PR is welcomed, thanks!

**Comment by markets** [comment]
oh yes! would be nice to support YT Shorts 👌🏼
