### ISSUE TITLE
undefined method `embed_code' for #<Youtube:0x007fd4c0f3e688>

### ISSUE THREAD

**Issue by b3ccio** [thibaudgg/video_info#38]
Hello,

I updated the video_info gem and I'm getting an undefined method for embed_code and embed_url on save. Anyone else having the same issue?

Thanks

**Comment by iantheparker** [comment]
Hello there, I'm getting this same error on version 2.6.1

**"undefined method `embed_code' for #<String:0x007fcae2200f08>"**

I'm using this, and the error is gone when I remove the embed_code()

`video = VideoInfo.new(video_url).embed_code(iframe_attributes: { width: 400, height: 350})`

Any ideas?

**Comment by iantheparker** [comment]
I just saved out another variable to manipulate with the embed_code function and got it working. Not sure why it doesn't like it all in one line though.

`video = VideoInfo.new(video_url)`
`embed_code = video.embed_code(iframe_attributes: { width: 400, height: 350})`

**Comment by vheuken** [comment]
@iantheparker That's interesting. Are you using the scraper or the API? If you didn't provide an API key, you're using the scraper.

**Comment by vheuken** [comment]
@iantheparker I just tried this using the scraper and it seems to work fine. I can test with an API key later tonight:

```ruby
2.3.0 :008 > u = "https://www.youtube.com/watch?v=AvnXan9vxCc"
 => "https://www.youtube.com/watch?v=AvnXan9vxCc" 
2.3.0 :009 > VideoInfo.new(u).embed_code(iframe_attributes: { width: 400, height: 350})
 => "<iframe src=\"//www.youtube.com/embed/AvnXan9vxCc\" frameborder=\"0\" allowfullscreen=\"allowfullscreen\" width=\"400\" height=\"350\"></iframe>" 
```

**Comment by iantheparker** [comment]
@vheuken I'm using the scraper. Still working fine while split into two lines though!

**Comment by vheuken** [comment]
@iantheparker Could you reproduce it in IRB and copy/paste both the line and the error? Because `"undefined method `embed_code' for #String:0x007fcae2200f08"` would imply you're calling `.embed_code` on a string, not a video object.
