### ISSUE TITLE
undefined method `url' for #<Object:0x007f807a8cd780>

### ISSUE THREAD

**Issue by juniovitorino** [thibaudgg/video_info#47]
In version 2.30 I'm getting this error with url method.

`2.0.0 (main):0 > v = VideoInfo.new 'http://www.youtube.com/watch?v=L7U6STcaCkU'
(pry) output error: #<NoMethodError: undefined method `url' for #<Object:0x007f807a8cd780>>`

**Comment by sayginburak** [comment]
Hi, @juniovitorino May I ask how did you solve this? We are getting this error too.
