### ISSUE TITLE
VimeoPro support

### ISSUE THREAD

**Issue by Calamari** [thibaudgg/video_info#61]
Hey ho.

I just came across VimeoPro. It'S Vimeo with customized pages, but it still allows for embeding the videos. Would be could when it would work, right?

An URL of VimeoPro looks something like: `http://vimeopro.com/talentrelations/studentwork/video/52377271`

Would that be something, that is easily achieved?

**Comment by thibaudgg** [comment]
Sounds good, could you submit a PR please?

**Comment by Calamari** [comment]
I'm not quite sure if I will have the time, but I could try.

**Comment by thibaudgg** [comment]
@Calamari Should I close it? No worries if you don't have time for it.

**Comment by Calamari** [comment]
I still would like to have it, but haven't got the time to do that yet. I guess there are more important things for me to do at the moment. :)

**Comment by thibaudgg** [comment]
@Calamari no worries feel free to submit a PR at any time, I'll close this issue in the meantime!
