### ISSUE TITLE
Error on getting title from youtube

### ISSUE THREAD

**Issue by GoodJob** [thibaudgg/video_info#69]
I'm getting all variables correctly from youtube video except the title.

I'm getting the result:
video.title = 'https://youtube.com/devicesupport'

whatever video I will choose from youtube. Maybe there is any solution? Thank you!

**Comment by thibaudgg** [comment]
Yeah @vheuken is actively working on it! :heart_eyes:

**Comment by isaeff** [comment]
@thibaudgg maybe using of some parser will be good temporary solution?

**Comment by vheuken** [comment]
@isaeff I'm writing the parser now. I'm setting aside time this weekend to finish it.

For now, you can pull from master and use the API to get the video title. Follow the instructions in README.md. It works well!

**Comment by thibaudgg** [comment]
Could you please try again with master branch, it should be fixed now.

**Comment by vheuken** [comment]
I'm marking this as fixed since the tests for this pass.

@GoodJob feel free to reopen this if you still have the issue on the master branch.
