### ISSUE TITLE
The youtube video duration is wrong

### ISSUE THREAD

**Issue by mwanas** [thibaudgg/video_info#70]
Trying any video duration is always giving 236 sec

**Comment by thibaudgg** [comment]
Hey thanks for opening this issue, it could be related to https://github.com/thibaudgg/video_info/pull/68

**Comment by mwanas** [comment]
what should I do to fix the issue ?

**Comment by thibaudgg** [comment]
I would wait that #68 has been merged, maybe you can try the branch in the meantime.

**Comment by vheuken** [comment]
@mwanas The issue is fixed on my branch so you can grab that code if you want.  You'll need to grab a youtube API key, though. There is documentation in the README in my branch on how to do this.

**Comment by thibaudgg** [comment]
@vheuken :+1:, thanks!

**Comment by thibaudgg** [comment]
@mwanas could you try the master branch and confirm that it works for you now? Thanks!
