### ISSUE TITLE
Vkontakte#available? returns true with private video

### ISSUE THREAD

**Issue by vheuken** [thibaudgg/video_info#71]
The issue is that it is giving a 200 response code.

``` ruby
  1) VideoInfo::Providers::Vkontakte#available? with private video available? should be falsey
     Failure/Error: its(:available?)       { should be_falsey }
       expected: falsey value
            got: true
     # ./spec/lib/video_info/providers/vkontakte_spec.rb:60:in `block (4 levels) in <top (required)>'
```

**Comment by thibaudgg** [comment]
Mmm could you point to Vkontakte API docs? That's weird it's just 200 or there is some body content?

**Comment by vheuken** [comment]
There is body content. It's just the HTML of the page you get when you go to a private video: http://vk.com/video9491528_165193133

It looks like it doesn't use an API, just scrapes the page. So I think I could just check for the "Error" and "Access denied" in the HTML.

**Comment by thibaudgg** [comment]
Sounds like a good idea. Go for old day scraping!

**Comment by vheuken** [comment]
Fixed in #72

**Comment by drakmail** [comment]
@vheuken thank you, just seems vkontakte broken again their HTML :angry:

**Comment by thibaudgg** [comment]
#72 merged, thanks @vheuken!
