### ISSUE TITLE
undefined method `provider_api_keys=' for VideoInfo:Class

### ISSUE THREAD

**Issue by tatsuaka** [thibaudgg/video_info#74]
Hello, 

Thanks for your useful gem.

I had a error when put 'VideoInfo.provider_api_keys = { youtube: 'YOUR_API_KEY' }' in new action in my controller. 'VideoInfo.new' is working properly.

I tried to update gem but is not resolved.

Where should I put youtube provider api keys?

**Comment by yongquanben** [comment]
I have encountered this problem as well. Could you share how you resolve this issue?

**Comment by tatsuaka** [comment]
As they write, just put the code in my controller 

def method_name
      VideoInfo.provider_api_keys = { youtube:  'YOUR_API_KEY'}
end

but, sometimes it's failed to get info 

I resolve to change url 'https' to 'http' also 'http' to 'https' thought this ways is not perfect.

I think it's not gem's fault. Youtube may be getting be evil...:)

Hope to helps you.

**Comment by yongquanben** [comment]
Thanks @tatsuaka 

Also found out in other issue that you should add this to your gemfile instead.

gem 'video_info', github: 'thibaudgg/video_info'

Hope it helps!
