### ISSUE TITLE
undefined method `provider_api_keys=' for VideoInfo:Class

### ISSUE THREAD

**Issue by HiteshSongra** [thibaudgg/video_info#77]
Hello,

I got this error.
undefined method `provider_api_keys=' for VideoInfo:Class

Here is code 
VideoInfo.provider_api_keys = { youtube: "XXXXXXXXXXXXXXXXXXXXXXXX" }

My Gemfile gem as 
- gem 'video_info', '~> 2.4.2'

**Comment by thibaudgg** [comment]
We didn't release master branch yet, please use:

 ```ruby
gem 'video_info', github: 'thibaudgg/video_info'
```

**Comment by HiteshSongra** [comment]
Thanks Thibaud,

It's resolved.

**Comment by ColdBlooder** [comment]
Where is the gemfile located? I'm kinda new to Ruby/gems and didn't have to edit a file before...

**Comment by thibaudgg** [comment]
@ColdBlooder you can learn more about `Gemfile` and Bundler here: http://bundler.io
