### ISSUE TITLE
HTTP 410 Gone on Youtube API

### ISSUE THREAD

**Issue by gottfrois** [thibaudgg/video_info#80]
I see that master branch has a new youtube API path. How stable is it? Because currently, using `2.4.2` version fetching video metadata on youtube return a `410 Gone` http request.

https://www.youtube.com/watch?v=rSQNi5sAwuc

**Comment by thibaudgg** [comment]
It should be quite stable, if you have any problems @vheuken is your man!

**Comment by sun-yr** [comment]
yeah, i got the same problem

**Comment by vheuken** [comment]
Yeah, the stuff in master should work fine. Just add `gem 'video_info', github: 'thibaudgg/video_info'` to your project's Gemfile. The new Youtube API requires an API key, so follow the instructions in this project's README.md for getting and setting the Youtube API key.

Note that I'm working on getting #79 merged, which will introduce a scraper so you won't have to get an API key for most things.

**Comment by whistlepost** [comment]
This is a silly question, but where does the VideoInfo.provider_api_keys go? In the model or initializer? If I set it after my VideoInfo.new(youtube_link) it throws an exception.

**Comment by vheuken** [comment]
@whistlepost You need to set it before you call VideoInfo.new. You just need to call it once.

**Comment by dbackeus** [comment]
Seems like a pretty serious bug, why not release the new version on rubygems?

**Comment by vheuken** [comment]
@dbackeus Youtube works (with the new API or with a scraper), but YoutubePlaylist isn't finished yet (well, API is, but not the scraper). I'm going to finish the scraper tonight and then he should release a new version.

**Comment by dbackeus** [comment]
Cool :+1:

**Comment by rafaelsales** [comment]
@vheuken News on this?

**Comment by vheuken** [comment]
@rafaelsales I'll be finishing it this weekend (there's just one more test failing), then he should be merging it and deploying a new version when he gets back  https://github.com/thibaudgg/video_info/pull/79#issuecomment-118269799

**Comment by thibaudgg** [comment]
Could you please try again with master branch, it should be fixed now.

**Comment by vheuken** [comment]
This should definitely be fixed in the master branch. Marking it as fixed.

If any of you still have an issue, feel free to reopen this.
