### ISSUE TITLE
Not working for Vimeo videos. 

### ISSUE THREAD

**Issue by shubhamkhanna** [thibaudgg/video_info#81]
Hi, 
I am trying to get vimeo videos api but facing with following issue.

OpenURI::HTTPError: 403 Forbidden

Could you please help ASAP.
Thanks!

**Comment by vheuken** [comment]
That's odd. I'll have a look tonight.

**Comment by thibaudgg** [comment]
@shubhamkhanna could you please provide a running code example, with a specific video id?

**Comment by shubhamkhanna** [comment]
@thibaudgg, thanks for writing  

on my console i did this,
irb(main):001:0> video = VideoInfo.new("http://vimeo.com/898029")
=> #<VideoInfo:0x00000007ea6148 @provider=#<VideoInfo::Providers::Vimeo:0x00000008083c68 @options={"User-Agent"=>"VideoInfo/2.4.2"}, @url="http://vimeo.com/898029", @video_id="898029">>
irb(main):002:0> video.title
OpenURI::HTTPError: 403 Forbidden
	from /home/bgosavi/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/open-uri.rb:346:in `open_http'
	from /home/bgosavi/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/open-uri.rb:776:in `buffer_open'
	from /home/bgosavi/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/open-uri.rb:203:in `block in open_loop'
	from /home/bgosavi/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/open-uri.rb:201:in `catch'
	from /home/bgosavi/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/open-uri.rb:201:in `open_loop'
	from /home/bgosavi/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/open-uri.rb:146:in `open_uri'
	from /home/bgosavi/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/open-uri.rb:678:in `open'
	from /home/bgosavi/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/open-uri.rb:33:in `open'
	from /home/bgosavi/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/gems/1.9.1/gems/video_info-2.4.2/lib/video_info/provider.rb:60:in `_set_data_from_api'
	from /home/bgosavi/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/gems/1.9.1/gems/video_info-2.4.2/lib/video_info/provider.rb:32:in `data'
	from /home/bgosavi/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/gems/1.9.1/gems/video_info-2.4.2/lib/video_info/providers/vimeo.rb:39:in `_video'
	from /home/bgosavi/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/gems/1.9.1/gems/video_info-2.4.2/lib/video_info/providers/vimeo.rb:13:in `block (2 levels) in <class:Vimeo>'
	from (irb):2
	from /home/bgosavi/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/gems/1.9.1/gems/railties-3.2.8/lib/rails/commands/console.rb:47:in `start'
	from /home/bgosavi/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/gems/1.9.1/gems/railties-3.2.8/lib/rails/commands/console.rb:8:in `start'
	from /home/bgosavi/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/gems/1.9.1/gems/railties-3.2.8/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'

 when i go for 'video.tile' i got error

**Comment by thibaudgg** [comment]
@shubhamkhanna have you also tried the master branch?

**Comment by shubhamkhanna** [comment]
Yup

**Comment by thibaudgg** [comment]
Ok thanks, let's see if @vheuken as some idea.

**Comment by shubhamkhanna** [comment]
does vimeo videos require any api key?

**Comment by thibaudgg** [comment]
It should not, maybe like YouTube they change that.

**Comment by shubhamkhanna** [comment]
Ohh..ok 

Thanks man!

**Comment by vheuken** [comment]
Strange. This works fine for me. Can you try putting `https` in the video url instead of `http`? It didn't matter for me but I'm not sure what else it could be.

**Comment by vheuken** [comment]
Also, can you try running this command:

`curl http://vimeo.com/api/v2/video/898029.json`

**Comment by shubhamkhanna** [comment]
@vheuken , @thibaudgg  finally its working.. :). it was network issue.

can I get author name of vimeo and dailymotion videos?

**Comment by vheuken** [comment]
That functionality currently isn't in this gem as far as I can tell. However, it looks like it is available via the API. If @thibaudgg would like it, I can add this after I finish #79 (should be done by the weekend).

**Comment by thibaudgg** [comment]
@vheuken would be awesome! :+1:

**Comment by shubhamkhanna** [comment]
Please  add like counts as well..

Thanks!

**Comment by shubhamkhanna** [comment]
@vheuken, any updates..?

**Comment by vheuken** [comment]
Not yet. I've been busier than expected. I'll make some time tonight though.

**Comment by thibaudgg** [comment]
@shubhamkhanna could you please try again with master branch?

**Comment by vheuken** [comment]
Since #87 got merged, I'll mark this as fixed.

@shubhamkhanna Feel free to reopen it if you still have trouble with it. It requires an API key now FYI.
