### ISSUE TITLE
Release Next version (v2.4.3?)

### ISSUE THREAD

**Issue by AknEp** [thibaudgg/video_info#82]
Why don't you release newer version?

**Comment by vheuken** [comment]
I'm legitimately working on finishing the last feature for this (Youtube scraper as an API alternative) right now. He has been waiting on that for awhile, but I haven't been able to find the time to finish.

**Comment by vheuken** [comment]
For now, though, you can still pull from master with:

`gem 'video_info', github: 'thibaudgg/video_info'`

You'll have to follow the instructions in the README to use the API key, though.

**Comment by AknEp** [comment]
Thank you for your quick reply!
yeah, I know github option & how to set API Key. It looks working enough :)

Thanks. I'm looking forward to next version.

**Comment by vheuken** [comment]
Feel free to watch #79 if you want to keep an eye on my progress. I'm currently a bit stuck but I'm sure I'll break through...

**Comment by thibaudgg** [comment]
Next release should be out soon!

**Comment by SkylerLipthay** [comment]
Hi! I'm in a particularly strange scenario where I can only source my gems from rubygems, so sourcing from master is unfortunately not an option. At the risk of sounding impatient, is there anything holding up the 2.4.3 release? Anything I can help with?

Thanks for everything, and a special thanks to @vheuken for all of your recent work on the YouTube scraper — seriously useful.

**Comment by thibaudgg** [comment]
@SkylerLipthay sorry to hear that, we're now waiting for #95 but I guess we could release 2.5.0 in the meantime. @vheuken what do you think?

**Comment by vheuken** [comment]
@thibaudgg I think we can do that, considering people seem more concerned about a new release than they do about having to get API keys for Vimeo and that I won't have time to work on #95 for at least a couple of days.

**Comment by thibaudgg** [comment]
2.5.0 has been released, thanks guys!

**Comment by SkylerLipthay** [comment]
Thank you both very much!

**Comment by AknEp** [comment]
Great! I'll update to 2.5.0 :tada:
