### ISSUE TITLE
Not available with valid url

### ISSUE THREAD

**Issue by itoufo** [thibaudgg/video_info#84]
Hi, 

I'm trying to use video_info in rails project.
But available? returns false with present youtube url like "http://www.youtube.com/watch?v=mZqGqE0D0n4"

I used like this
config/initializers/video_info.rb
``` 
VideoInfo.provider_api_keys = { youtube: ' *** valid api key *** ' }
VideoInfo.disable_providers = %w[dailymotion wistia]
```

model/video.rm
```
validate do
    begin
      video = VideoInfo.new(video_url)
      if video_url.present? && ! video.available?
        p video
        p video.available?
        errors.add(:video_url, "seems to be invalid")
      end
    rescue VideoInfo::UrlError
      errors.add(:video_url, "is invalid")
    end
end
```

Outputs are below.
```
"http://www.youtube.com/watch?v=mZqNqE0p0n4"
#<VideoInfo:0x007f7ff2c7ea88 @provider=#<VideoInfo::Providers::Youtube:0x007f7ff2c7e308 @options={"User-Agent"=>"VideoInfo/2.4.2"}, @url="http://www.youtube.com/watch?v=mZqNqE0p0n4", @video_id="mZqNqE0p0n4">>
false
```

Looking forward to hearing from you soon.
Thank you!

**Comment by thibaudgg** [comment]
Did you try with the master branch or PR #79? There's some work on process with YouTube

**Comment by vheuken** [comment]
@itoufo This should be fixed in the master branch, so I'm closing it. If you still have issues on the master branch, feel free to let me know!
