### ISSUE TITLE
Private video used in vkontakte spec isn't private anymore

### ISSUE THREAD

**Issue by vheuken** [thibaudgg/video_info#89]
The spec for testing `Vkontakte#available?` against private videos is failing because the video used seems to not be private anymore. It needs to be replaced by a private video, but I can't find a link to a private Vkontakte video. 

The URL to the video is:
http://vk.com/video9491528_165193133

**Comment by thibaudgg** [comment]
@drakmail could you provide a private Vkontakte video url? Thanks!

**Comment by drakmail** [comment]
Heh, funny. Private video, hosted from my account: http://vk.com/video39576223_166315543

**Comment by thibaudgg** [comment]
@drakmail thanks for the private link!

**Comment by vheuken** [comment]
Fixed in #92
