### ISSUE TITLE
SSL issues with Jruby (only on Travis-CI)

### ISSUE THREAD

**Issue by vheuken** [thibaudgg/video_info#90]
20 Vkontakte specs fail with jruby and nowhere else.

They all seem to have the same error, which seems to be related to SSL:

```
Java::JavaLang::RuntimeException:
  Could not generate DH keypair
```

**UPDATE:** read thread for new details.

**Comment by drakmail** [comment]
Thanks for report, I'm investigate it tomorrow (finally I'm have a chance to try jruby 9000 :smile: )

**Comment by thibaudgg** [comment]
@drakmail thanks for having a look at it, that should be the last blocker for a new release!

**Comment by vheuken** [comment]
I just tested with jruby 9  on my machine and it works fine. However, it still fails with jruby 9 on travis-ci.

I think Travis might be using an older version of jdk or something and that is screwing it up. Just a guess, though.

**Comment by vheuken** [comment]
This might be fixed when #97 is handled. I'll be looking at that again soon.

**Comment by vheuken** [comment]
Nope, looks like handling #97 didn't fix it.

**Comment by vheuken** [comment]
Right now the issue seems to be that jruby on Travis will always use `jruby 1.7.19 (1.9.3p551)` *even if you explicitly tell it to use jruby-9000 or jruby-head`.

Should probably be reported to Travis-ci.

**Comment by vheuken** [comment]
Okay, figured out how to get jruby-9000 working on Travis. Still a ton of weird SSL issues though. It works fine on my machine, though, so this must be a Travis-CI issue.

**Comment by vheuken** [comment]
So, I'm not totally sure of a solution since I really don't fully understand the problem. Regardless, jruby works fine on my machine, and jruby is already an "allowed failure". Perhaps we should close this issue. What do you think, @thibaudgg?

**Comment by vheuken** [comment]
Also, Rubinus passes on Travis-CI now. Maybe we should stop that from being an allowed failure now? I'm not sure how many people still use Rubinous (I don't really follow Ruby anymore), but it might be nice to say that we support it if only because it implies our code is portable and of high quality,

**Comment by vheuken** [comment]
Actually, I just noticed that all of the failing Jruby specs are due to Vkontakte. I think I will spend some time next week investigating why that is.

**Comment by vheuken** [comment]
@drakmail You wrote the Vkontakte code, no? Any ideas on what could be going on?

**Comment by vheuken** [comment]
I could be wrong, but it looks like you're just scraping the page. Maybe we should port this over to how Oga handles it, because that's what we use for VimeoScraper and YoutubeScraper. If nobody objects, I think I'll try and do that next week sometime.

**Comment by vheuken** [comment]
Okay, sorry. I jumped to conclusions too fast. The code is fine, and the issue doesn't seem like it can be solved by that. I'll keep investigating.

**Comment by vheuken** [comment]
I just fixed the issue. There is an option in Travis to update to JDK 8. Seems to work now!
