### ISSUE TITLE
undefined method `provider_api_keys' for VideoInfo:Class (NoMethodError)

### ISSUE THREAD

**Issue by mrchess** [thibaudgg/video_info#91]
I created a brand new project.

Gemfile has `gem 'video_info', github: 'thibaudgg/video_info'`

But when I do:

```
require 'video_info'

VideoInfo.provider_api_keys = { youtube: 'MY_KEY' }
```
It throws the 
`undefined method 'provider_api_keys' for VideoInfo:Class (NoMethodError)`

I'm positive I'm using the master verison as my Gemfile.lock says:

```
GIT
  remote: git://github.com/thibaudgg/video_info.git
  revision: 002bcc4161c6d296c1fe59b201de00fb9071b4ed
  branch: master
  specs:
    video_info (2.4.2)
      addressable
      htmlentities
      iso8601
      multi_json (~> 1.11)
      oga
      open_uri_redirections
```

**Comment by vheuken** [comment]
That's odd. Are you sure you don't have an earlier version installed that might be being used instead? 

Try again after this and see if it helps:
```
gem uninstall video_info
bundle clean
bundle install```

**Comment by mrchess** [comment]
Sorry, my error. I didn't realize this when installing gems off git:

http://stackoverflow.com/questions/26950906/issue-with-require-gem-when-passing-git-repo-to-gem-in-gemfile
