### ISSUE TITLE
add spec/fixtures to gitignore

### ISSUE THREAD

**Issue by vheuken** [thibaudgg/video_info#93]
Is there any reason spec/fixtures isn't in the gitignore? I've noticed that some are committed but I don't see why they're there.

It's kinda annoying to see this every `git status` : 
![](http://i.imgur.com/xbA7wdH.png)

**Comment by thibaudgg** [comment]
The idea was to only re-record VCR cassette [every week](https://github.com/thibaudgg/video_info/blob/master/spec/spec_helper.rb#L15), but we could remove them completely, it would make sense here. :+1:

**Comment by vheuken** [comment]
Done and in master.
