### ISSUE TITLE
Getting a NameError (uninitialized constant error

### ISSUE THREAD

**Issue by AppyCat** [thibaudgg/video_info#94]
The code below works fine in development mode using ruby 2.2.0 

However on my production server using ruby 2.1.2 I get the following error:

I, [2015-08-02T01:11:12.742798 #5361]  INFO -- : Completed 500 Internal Server Error in 52ms (ActiveRecord: 8.8ms)
F, [2015-08-02T01:11:12.743799 #5361] FATAL -- : 
NameError (uninitialized constant Admin::ChampionPhotosController::VideoInfo):
 app/controllers/admin/champion_photos_controller.rb:35:in `block in create'
 app/controllers/admin/champion_photos_controller.rb:31:in `create’

Here’s my code to add the large vimeo thumbnail to the db and upload via carrier wave.

	unless @admin_champion_photo.video.blank?
         video_image = VideoInfo.new("#{@admin_champion_photo.video}")
         thumbnail = Admin::ChampionPhoto.find(@admin_champion_photo.id)
         thumbnail.remote_photo_url = video_image.thumbnail_large
         thumbnail.save
       end

Could it be a ruby version issue or something else I'm missing on the production side?

I added it to the server as gem install video_info

Then as an added measure also to the gem file as gem 'video_info' and ran bundle install.

**Comment by vheuken** [comment]
What provider are you using for the video url (Youtube, Vimeo, etc)?

>I added it to the server as gem install video_info

Have you tried the master branch? The version in Rubygems is outdated and will be updated very soon.

**Comment by AppyCat** [comment]
I'm using vimeo with this url:

https://vimeo.com/81486075

**Comment by vheuken** [comment]
Have you tried the master branch yet?

It looks like this could be related to issue #81, which I believe is fixed in PR #87, which we're waiting to be rebased with master. If that doesn't get done tomorrow I'll try to rebase it myself.

**Comment by AppyCat** [comment]
Thanks and yes I just tried the master branch and got the same error on the server. Only diff between development where it works and production is the ruby version. 2.2.0 in dev and 2.1.2 in production.

I use rbenv on production and it croaks when I tr to upgrade to ruby 2.2.0. So could go back a ruby version or wait until you rebase the master.

**Comment by vheuken** [comment]
I believe @thibaudgg decided to only officially support 2.2.0+ (correct me if I'm wrong), so upgrading to 2.2 would be the optimal path. However, if #87 doesn't fix the issue and upgrading to 2.2 still isn't an option for you, I'll spend some time looking into your issue.

**Comment by thibaudgg** [comment]
We could add back 2.1 if you want, but in most cases upgrading from 2.1 to 2.2 should be smooth, Rails 5 will only support 2.2 so I'm not sure it makes much sense to stay with 2.1.

**Comment by AppyCat** [comment]
Thank you for clarifying that. I think it would be better for me to upgrade to  2.2.0, I'll drop rbenv as it doesn't install its 2.2.0-dev version. If you can out on the intro that its 2.2+ compatible, that will help the next person with similar issue.

Would you recommend using rvm instead in production or do a system wide ruby 2.2 install?

**Comment by thibaudgg** [comment]
It depends your deployment setup but going with rvm/rbenv/chruby should be fine.

**Comment by AppyCat** [comment]
rbenv and rvm bit temperamental, so did a 2.2.2 build and video_info working nice and smooth.

**Comment by thibaudgg** [comment]
:+1:
