### ISSUE TITLE
New Travis-CI infrastructure causes 429 (Too many requests) HTTP error

### ISSUE THREAD

**Issue by vheuken** [thibaudgg/video_info#97]
I tried to update to the new Travis-CI infrastructure, but it causes the Youtube scraper to give 429 HTTP errors. I imagine Youtube, for whatever reason, just blocked that IP.

This isn't an issue on the legacy infrastructure, but we should let Travis know and see if they have a solution, since the legacy infrastructure will surely be removed eventually. 

If they can't fix it, we could try using a proxy I guess. We could also download the Youtube pages manually and use them in mocks, but that means we wouldn't know if Youtube makes any HTML changes that break things.

**Comment by thibaudgg** [comment]
Too bad, we should definitely let Travis-CI about that issue! Could you take care of it?

**Comment by vheuken** [comment]
This is not an issue anymore apparently. We're now using Travis-CI's new infrastructure. It seems to be much faster!
