### ISSUE TITLE
Uninitialized constant error in production

### ISSUE THREAD

**Issue by AppyCat** [thibaudgg/video_info#99]
I am getting the same uninitialized constant error on my production server that has ruby 2.2.2 and Rails 4.2.3. Exact same settings on my development laptop work just fine, but not so on the server. 

Production server OS is Debian Wheezy. Here's the error in the production log file:

NameError (uninitialized constant Admin::ReelsController::VideoInfo):
  app/controllers/admin/reels_controller.rb:58:in `block in update'
  app/controllers/admin/reels_controller.rb:54:in `update'

And here's the code in my create method:

unless @admin_reel.reel.blank? && @admin_reel.photo == ''
          video = VideoInfo.provider_api_keys = { vimeo: 'my_key_info_removed_here' }
          video = VideoInfo.new("#{@admin_reel.reel}")
          video_image = Admin::Reel.find(@admin_reel.id)
          video_image.remote_photo_url = video.thumbnail_large
          video_image.save
        end

In my gemfile:

gem 'video_info', :git => 'https://github.com/thibaudgg/video_info.git'

I also did a system install:

gem install video_info

**Comment by vheuken** [comment]
It sounds like you didn't put `require 'video_info'` at the top of the file.

**Comment by AppyCat** [comment]
Thank you, that fixed it.
